// frontend/src/features/integrations/integration-section.tsx
import * as React from 'react'

interface IntegrationSectionProps {
  title: string
  description?: string
  children: React.ReactNode
}

function IntegrationSection({ title, description, children }: IntegrationSectionProps) {
  return (
    <section className="mb-12">
      <div className="mb-6">
        <h2 className="text-xl font-bold tracking-tight text-slate-900 dark:text-white">
          {title}
        </h2>
        {description && (
          <p className="text-sm text-slate-500">{description}</p>
        )}
      </div>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
        {children}
      </div>
    </section>
  )
}

export { IntegrationSection }

// frontend/src/routes/settings/integrations/components/integration-section.svelte
<script lang="ts">
	import type { Snippet } from 'svelte'

	let { title, description, children } = $props<{
		title: string
		description?: string
		children: Snippet
	}>()
</script>

<section class="mb-12">
	<div class="mb-6">
		<h2 class="text-xl font-bold tracking-tight text-slate-900 dark:text-white">
			{title}
		</h2>
		{#if description}
			<p class="text-sm text-slate-500">
				{description}
			</p>
		{/if}
	</div>
	<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
		{@render children()}
	</div>
</section>
