// frontend/src/lib/components/ui/container/container.svelte
<script lang="ts">
	import type { Snippet } from 'svelte'
	import type { HTMLAttributes } from 'svelte/elements';

    let {
        class: className = '',
        children,
        ...restProps
    }: HTMLAttributes<HTMLDivElement> & {
        children: Snippet
    } = $props()
</script>

<div class="mx-auto max-w-full w-full lg:w-[1200px] xl:w-[1600px] px-2 lg:px-4 {className}" {...restProps}>
    {@render children()}
</div>

// frontend/src/components/container.tsx
import React from 'react'
import { cn } from '@/lib/utils'

function Container({ className, children, ...rest }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn('mx-auto w-full max-w-full px-2 lg:w-[1200px] lg:px-4 xl:w-[1600px]', className)}
      {...rest}
    >
      {children}
    </div>
  )
}

export { Container }
