// frontend/src/lib/components/ui/card/connection/card-add.svelte
<script lang="ts">
	import type { ProviderSchema } from '$lib/api/integrations'
	import ProviderIcon from '$lib/components/ui/provider-icon.svelte'
	import { LucideBook } from 'lucide-svelte'
    import type { Component } from 'svelte'
    import Card from '$lib/components/ui/card/connection/card.svelte'
    import FooterBtn from '$lib/components/ui/card/connection/card-footer-btn.svelte'

	let { provider, onclick } = $props<{
		provider: ProviderSchema
		onclick: () => void
	}>()
</script>

<Card variant="border">
    <div class="flex flex-row gap-2 items-start justify-start p-4">
        <div class="w-16 h-16 p-2 shrink-0 bg-slate-500/10 border border-slate-500/15 rounded-lg flex items-center justify-center">
            <ProviderIcon 
                provider={provider.provider} 
                logoSvg={provider.logo_svg}
                logoPng={provider.logo_png}
            />
        </div>
        <div class="flex flex-col">
            <h3 class="text-base font-semibold text-slate-900 dark:text-slate-100">
                {provider.display_name}
            </h3>
            <p class="text-xs text-slate-400">
                {provider.description}
            </p>
        </div>
    </div>
    {#snippet footer()}
        <div class="text-[10px] text-slate-200 font-bold mr-auto uppercase">
            #{provider.group.replace('_', '-')}
        </div>
        <FooterBtn
            href="#"
            variant="ghost"
            label="Read docs"
            icon={LucideBook}
        />
        <FooterBtn
            onclick={onclick}
            variant="primary"
            label="Add Connection"
        />
    {/snippet}
</Card>

// frontend/src/features/integrations/card-add.tsx
import { useTranslation } from 'react-i18next'
import { Book } from 'lucide-react'
import { ProviderIcon } from '@/components/provider-icon'
import type { ProviderSchema } from '@/lib/api/integrations'
import { ConnectionCard } from './connection-card'
import { CardFooterBtn } from './card-footer-btn'

interface CardAddProps {
  provider: ProviderSchema
  onClick: () => void
}

function CardAdd({ provider, onClick }: CardAddProps) {
  const { t } = useTranslation('integrations')

  const footer = (
    <>
      <div className="mr-auto text-[10px] font-bold text-slate-200 uppercase">
        #{provider.group.replace('_', '-')}
      </div>
      <CardFooterBtn href="#" variant="ghost" label={t('read_docs')} icon={Book} />
      <CardFooterBtn onClick={onClick} variant="primary" label={t('add_connection')} />
    </>
  )

  return (
    <ConnectionCard variant="border" footer={footer}>
      <div className="flex flex-row items-start justify-start gap-2 p-4">
        <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-lg border border-slate-500/15 bg-slate-500/10 p-2">
          <ProviderIcon
            provider={provider.provider}
            logoSvg={provider.logo_svg}
            logoPng={provider.logo_png}
          />
        </div>
        <div className="flex flex-col">
          <h3 className="text-base font-semibold text-slate-900 dark:text-slate-100">
            {provider.display_name}
          </h3>
          <p className="text-xs text-slate-400">{provider.description}</p>
        </div>
      </div>
    </ConnectionCard>
  )
}

export { CardAdd }
