// frontend/src/routes/settings/integrations.tsx
import { createFileRoute, redirect } from '@tanstack/react-router'
import { useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { useQuery } from '@tanstack/react-query'
import { toast } from 'sonner'
import { useAuth } from '@/store/auth'
import { getIntegrations } from '@/lib/api/integrations'
import { getTenants } from '@/lib/api/tenants'
import { qk, fallbackQuery } from '@/lib/query'
import { useIntegrationManager } from '@/features/integrations/use-integration-manager'
import { IntegrationSection } from '@/features/integrations/integration-section'
import { CardConnected } from '@/features/integrations/card-connected'
import { CardAdd } from '@/features/integrations/card-add'
import { IntegrationFilters } from '@/features/integrations/integration-filters'
import { IntegrationModal } from '@/features/integrations/integration-modal'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { Skeleton } from '@/components/ui/skeleton'

export const Route = createFileRoute('/settings/integrations')({
  beforeLoad: () => {
    if (!useAuth.getState().isAuthenticated()) {
      throw redirect({ to: '/login' })
    }
  },
  validateSearch: (s) => ({
    connected: s.connected as string | undefined,
    provider_name: s.provider_name as string | undefined,
  }),
  component: IntegrationsRoute,
})

function IntegrationsRoute() {
  const { t } = useTranslation('integrations')

  const integrationsQuery = useQuery({
    queryKey: qk.integrations,
    queryFn: () =>
      fallbackQuery(() => getIntegrations(), { integrations: [], providers: [] }),
  })

  const tenantsQuery = useQuery({
    queryKey: qk.tenants,
    queryFn: () => fallbackQuery(() => getTenants(), []),
  })

  const manager = useIntegrationManager()

  useEffect(() => {
    if (integrationsQuery.data && tenantsQuery.data) {
      manager.init({
        data: Promise.resolve(integrationsQuery.data),
        tenants: Promise.resolve(tenantsQuery.data),
      })
    }
  }, [integrationsQuery.data, tenantsQuery.data])

  useEffect(() => {
    if (manager.justConnected) {
      toast.success(manager.connectedMessage)
    }
  }, [manager.justConnected, manager.connectedMessage])

  return (
    <>
      <div className='w-full px-4 py-8 sm:px-6 lg:px-8' data-testid='integrations-page'>
        {manager.isLoading ? (
          <div className='space-y-8'>
            {Array.from({ length: 2 }, (_, sectionIdx) => (
              <section key={sectionIdx}>
                <Skeleton className='mb-3 h-4 w-24' />
                <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4'>
                  {Array.from({ length: 8 }, (_, cardIdx) => (
                    <div
                      key={cardIdx}
                      className='flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900'
                    >
                      <div className='flex items-center gap-2.5'>
                        <Skeleton className='h-8 w-8 rounded-lg' />
                        <div className='flex-1 space-y-2'>
                          <Skeleton className='h-4 w-24' />
                          <Skeleton className='h-3 w-16' />
                        </div>
                      </div>
                      <Skeleton className='mt-2 h-4 w-full' />
                    </div>
                  ))}
                </div>
              </section>
            ))}
          </div>
        ) : (
          <>
            {manager.integrations.length > 0 && (
              <IntegrationSection
                title={t('connected_title')}
                description={t('connected_desc')}
              >
                {manager.integrations.map((integration) => {
                  const provider = manager.providerForIntegration(integration)
                  if (!provider) return null
                  return (
                    <CardConnected
                      key={integration.id}
                      integration={integration}
                      provider={provider}
                      tenantOptions={manager.tenantOptions}
                      onEdit={() => manager.openEdit(integration, provider)}
                      onDelete={() => manager.confirmDelete(integration.id)}
                      onConnect={() => manager.handleConnect(integration.id)}
                    />
                  )
                })}
              </IntegrationSection>
            )}

            <section className='mb-8'>
              <div className='mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between'>
                <div>
                  <h2 className='text-xl font-bold tracking-tight text-slate-900 dark:text-white'>
                    {t('browse_title')}
                  </h2>
                  <p className='text-sm text-slate-500'>{t('browse_desc')}</p>
                </div>
                <IntegrationFilters
                  searchQuery={manager.searchQuery}
                  onSearchChange={manager.setSearchQuery}
                  selectedCategory={manager.selectedCategory}
                  onCategoryChange={manager.setSelectedCategory}
                  categories={manager.GROUP_ORDER}
                  categoryLabels={manager.GROUP_LABELS}
                  onClear={manager.clearFilters}
                />
              </div>

              {manager.providers.length === 0 ? (
                <div className='rounded-xl border border-dashed border-slate-200 p-12 text-center dark:border-slate-700'>
                  <p className='text-sm text-slate-400'>{t('no_providers')}</p>
                </div>
              ) : manager.filteredProviders.length > 0 ? (
                <div className='grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4'>
                  {manager.filteredProviders.map((provider) => (
                    <CardAdd
                      key={provider.provider}
                      provider={provider}
                      onClick={() => manager.openCreate(provider)}
                    />
                  ))}
                </div>
              ) : (
                <div className='rounded-xl border border-dashed border-slate-200 p-12 text-center dark:border-slate-700'>
                  <p className='text-sm text-slate-400'>{t('no_match')}</p>
                  <button
                    onClick={manager.clearFilters}
                    className='mt-2 text-sm font-medium text-indigo-600 hover:underline'
                  >
                    {t('clear_all_filters')}
                  </button>
                </div>
              )}
            </section>
          </>
        )}
      </div>

      <IntegrationModal
        manager={manager}
        onSave={() => manager.handleSave()}
        onTest={manager.handleTest}
      />

      <ConfirmDialog
        open={manager.showDelete}
        onOpenChange={manager.setShowDelete}
        title={t('delete_title')}
        description={t('delete_desc')}
        confirmLabel={t('delete_confirm')}
        isLoading={manager.isDeleting}
        onConfirm={manager.handleDelete}
      />
    </>
  )
}

// frontend/src/routes/settings/integrations/+page.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner'
	import { m } from '$lib/paraglide/messages'
	import Skeleton from '$lib/components/ui/skeleton.svelte'
	import ConfirmDialog from '$lib/components/ui/dialog/confirm-dialog.svelte'
	import type { PageData } from './$types'
	import CardAdd from '$lib/components/ui/card/connection/card-add.svelte'
	import CardConnected from '$lib/components/ui/card/connection/card-connected.svelte'
	import { IntegrationManager } from './integrations.svelte'
	import IntegrationFilters from './components/integration-filters.svelte'
	import IntegrationSection from './components/integration-section.svelte'
	import IntegrationModal from './components/integration-modal.svelte'

	let { data } = $props<{ data: PageData }>()

	const manager = new IntegrationManager()

	$effect(() => {
		manager.init(data)
	})

	$effect(() => {
		if (manager.justConnected) toast.success(manager.connectedMessage)
	})
</script>

<div class="w-full px-4 py-8 sm:px-6 lg:px-8">
	{#if manager.isLoading}
		<div class="space-y-8">
			{#each Array(2) as _, i (i)}
				<section>
					<Skeleton class="mb-3 h-4 w-24" />
					<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
						{#each Array(8) as _, j (j)}
							<div
								class="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"
							>
								<div class="flex items-center gap-2.5">
									<Skeleton class="h-8 w-8 rounded-lg" />
									<div class="flex-1 space-y-2">
										<Skeleton class="h-4 w-24" />
										<Skeleton class="h-3 w-16" />
									</div>
								</div>
								<Skeleton class="mt-2 h-4 w-full" />
							</div>
						{/each}
					</div>
				</section>
			{/each}
		</div>
	{:else}
		{#if manager.integrations.length > 0}
			<IntegrationSection title={m['integrations:connected_title']()} description={m['integrations:connected_desc']()}>
				{#each manager.integrations as integration (integration.id)}
					{@const provider = manager.providerForIntegration(integration)}
					{#if provider}
						<CardConnected
							{integration}
							{provider}
							tenantOptions={manager.tenantOptions}
							onEdit={() => manager.openEdit(integration, provider)}
							onDelete={() => manager.confirmDelete(integration.id)}
							onConnect={() => manager.handleConnect(integration.id)}
						/>
					{/if}
				{/each}
			</IntegrationSection>
		{/if}

		<section class="mb-8">
			<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
				<div>
					<h2 class="text-xl font-bold tracking-tight text-slate-900 dark:text-white">
						{m['integrations:browse_title']()}
					</h2>
					<p class="text-sm text-slate-500">{m['integrations:browse_desc']()}</p>
				</div>

				<IntegrationFilters
					bind:searchQuery={manager.searchQuery}
					bind:selectedCategory={manager.selectedCategory}
					categories={manager.GROUP_ORDER}
					categoryLabels={manager.GROUP_LABELS}
					onClear={() => manager.clearFilters()}
				/>
			</div>

			{#if manager.filteredProviders.length > 0}
				<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
					{#each manager.filteredProviders as provider (provider.provider)}
						<CardAdd {provider} onclick={() => manager.openCreate(provider)} />
					{/each}
				</div>
			{:else}
				<div
					class="rounded-xl border border-dashed border-slate-200 p-12 text-center dark:border-slate-700"
				>
					<p class="text-sm text-slate-400">{m['integrations:no_match']()}</p>
					<button
						onclick={() => manager.clearFilters()}
						class="mt-2 text-sm font-medium text-indigo-600 hover:underline"
					>
						{m['integrations:clear_all_filters']()}
					</button>
				</div>
			{/if}
		</section>

		{#if manager.providers.length === 0}
			<div
				class="rounded-xl border border-dashed border-slate-200 p-12 text-center dark:border-slate-700"
			>
				<p class="text-sm text-slate-400">{m['integrations:no_providers']()}</p>
			</div>
		{/if}
	{/if}
</div>

<IntegrationModal
	{manager}
	onSave={() => manager.handleSave()}
	onTest={() => manager.handleTest()}
/>

<ConfirmDialog
	bind:open={manager.showDelete}
	title={m['integrations:delete_title']()}
	description={m['integrations:delete_desc']()}
	confirmLabel={m['integrations:delete_confirm']()}
	isLoading={manager.isDeleting}
	onconfirm={() => manager.handleDelete()}
/>
