// frontend/src/routes/[tenant]/ads/google/live/[campaign_id]/components/device-breakdown.svelte
<script lang="ts">
	import { Chart, registerables } from 'chart.js'
	import type { DeviceRow } from '$lib/api/campaigns'
	import { m } from '$lib/paraglide/messages'

	Chart.register(...registerables)

	let { devices } = $props<{ devices: DeviceRow[] }>()

	const DEVICE_COLORS: Record<string, string> = {
		DESKTOP: '#3b82f6',
		MOBILE: '#22c55e',
		TABLET: '#f59e0b'
	}

	const deviceLabel = (d: string) =>
		d === 'DESKTOP'
			? m['ads:analytics.device_desktop']()
			: d === 'MOBILE'
				? m['ads:analytics.device_mobile']()
				: m['ads:analytics.device_tablet']()

	const donutConfig = $derived(() => ({
		type: 'doughnut' as const,
		data: {
			labels: devices.map((d: DeviceRow) => deviceLabel(d.device)),
			datasets: [
				{
					data: devices.map((d: DeviceRow) => d.cost),
					backgroundColor: devices.map((d: DeviceRow) => DEVICE_COLORS[d.device] ?? '#94a3b8'),
					borderWidth: 0
				}
			]
		},
		options: {
			responsive: true,
			maintainAspectRatio: false,
			plugins: {
				legend: { position: 'bottom' as const },
				tooltip: {
					callbacks: {
						label: (ctx: { parsed: number }) => ` R$${ctx.parsed.toFixed(2)}`
					}
				}
			}
		}
	}))

	const cpaDevices = $derived(
		devices
			.filter((d: DeviceRow) => d.conversions > 0)
			.sort((a: DeviceRow, b: DeviceRow) => a.cpa - b.cpa)
	)

	let canvas = $state<HTMLCanvasElement | undefined>()
	let instance: Chart<'doughnut'> | null = null

	$effect(() => {
		if (!canvas || devices.length === 0) return
		instance?.destroy()
		instance = new Chart(canvas, donutConfig())
		return () => {
			instance?.destroy()
			instance = null
		}
	})
</script>

<div
	class="space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"
>
	<div>
		<h3 class="text-lg font-bold text-slate-900 dark:text-white">{m['ads:analytics.device_title']()}</h3>
		<p class="mt-0.5 text-xs text-slate-400">{m['ads:analytics.device_subtitle']()}</p>
	</div>

	{#if devices.length === 0}
		<p class="py-8 text-center text-sm text-slate-400">{m['ads:analytics.device_empty']()}</p>
	{:else}
		<div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
			<div>
				<p class="mb-3 text-sm font-medium text-slate-600 dark:text-slate-400">{m['ads:analytics.device_cost_share']()}</p>
				<div class="h-[220px]">
					<canvas bind:this={canvas}></canvas>
				</div>
			</div>

			{#if cpaDevices.length > 0}
				<div>
					<p class="mb-3 text-sm font-medium text-slate-600 dark:text-slate-400">{m['ads:analytics.device_cpa_chart']()}</p>
					<div class="space-y-3">
						{#each cpaDevices as d (d.device)}
							{@const maxCpa = cpaDevices[cpaDevices.length - 1].cpa}
							<div class="space-y-1">
								<div class="flex justify-between text-xs text-slate-600 dark:text-slate-300">
									<span>{deviceLabel(d.device)}</span>
									<span class="font-semibold">R${d.cpa.toFixed(2)}</span>
								</div>
								<div class="h-2 rounded-full bg-slate-100 dark:bg-slate-800">
									<div
										class="h-2 rounded-full transition-all"
										style="width: {maxCpa > 0
											? ((d.cpa / maxCpa) * 100).toFixed(1)
											: 0}%; background: {DEVICE_COLORS[d.device] ?? '#94a3b8'}"
									></div>
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/if}
		</div>
	{/if}
</div>

// frontend/src/components/ads-live/device-breakdown.tsx
import { useMemo } from 'react'
import { Doughnut } from 'react-chartjs-2'
import type { ChartConfiguration } from 'chart.js'
import { useTranslation } from 'react-i18next'
import type { DeviceRow } from '@/lib/api/campaigns'
import '@/lib/utils/chart-setup'

const DEVICE_COLORS: Record<string, string> = {
  DESKTOP: '#3b82f6',
  MOBILE: '#22c55e',
  TABLET: '#f59e0b',
}

export function DeviceBreakdown({ devices }: { devices: DeviceRow[] }) {
  const { t } = useTranslation('ads')

  const deviceLabel = (d: string) =>
    d === 'DESKTOP'
      ? t('analytics.device_desktop')
      : d === 'MOBILE'
        ? t('analytics.device_mobile')
        : t('analytics.device_tablet')

  const donutConfig = useMemo<ChartConfiguration<'doughnut'>>(
    () => ({
      type: 'doughnut',
      data: {
        labels: devices.map((d) => deviceLabel(d.device)),
        datasets: [
          {
            data: devices.map((d) => d.cost),
            backgroundColor: devices.map((d) => DEVICE_COLORS[d.device] ?? '#94a3b8'),
            borderWidth: 0,
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: { position: 'bottom' },
          tooltip: {
            callbacks: {
              label: (ctx) => ` R$${ctx.parsed.toFixed(2)}`,
            },
          },
        },
      },
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [devices, t],
  )

  const cpaDevices = useMemo(
    () => devices.filter((d) => d.conversions > 0).sort((a, b) => a.cpa - b.cpa),
    [devices],
  )

  return (
    <div className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <div>
        <h3 className="text-lg font-bold text-slate-900 dark:text-white">
          {t('analytics.device_title')}
        </h3>
        <p className="mt-0.5 text-xs text-slate-400">{t('analytics.device_subtitle')}</p>
      </div>

      {devices.length === 0 ? (
        <p className="py-8 text-center text-sm text-slate-400">{t('analytics.device_empty')}</p>
      ) : (
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          <div>
            <p className="mb-3 text-sm font-medium text-slate-600 dark:text-slate-400">
              {t('analytics.device_cost_share')}
            </p>
            <div className="h-[220px]">
              <Doughnut data={donutConfig.data} options={donutConfig.options} />
            </div>
          </div>

          {cpaDevices.length > 0 && (
            <div>
              <p className="mb-3 text-sm font-medium text-slate-600 dark:text-slate-400">
                {t('analytics.device_cpa_chart')}
              </p>
              <div className="space-y-3">
                {cpaDevices.map((d) => {
                  const maxCpa = cpaDevices[cpaDevices.length - 1].cpa
                  return (
                    <div key={d.device} className="space-y-1">
                      <div className="flex justify-between text-xs text-slate-600 dark:text-slate-300">
                        <span>{deviceLabel(d.device)}</span>
                        <span className="font-semibold">R${d.cpa.toFixed(2)}</span>
                      </div>
                      <div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800">
                        <div
                          className="h-2 rounded-full transition-all"
                          style={{
                            width: `${maxCpa > 0 ? ((d.cpa / maxCpa) * 100).toFixed(1) : 0}%`,
                            background: DEVICE_COLORS[d.device] ?? '#94a3b8',
                          }}
                        />
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
