// frontend/src/routes/[tenant]/ads/google/live/[campaign_id]/components/skeleton.svelte
<div class="pb-4 flex flex-col lg:flex-row items-end justify-between gap-4 border-b border-white/10 animate-pulse">
    <div class="flex flex-col gap-2">
        <div class="h-4 w-4 rounded bg-slate-200 dark:bg-slate-700"></div>
        <div class="h-10 w-72 rounded-lg bg-slate-200 dark:bg-slate-700"></div>
        <div class="flex gap-2">
            <div class="h-5 w-24 rounded bg-slate-100 dark:bg-slate-800"></div>
            <div class="h-5 w-16 rounded bg-slate-100 dark:bg-slate-800"></div>
        </div>
    </div>
    <div class="flex gap-2">
        <div class="h-8 w-20 rounded-md bg-slate-100 dark:bg-slate-800"></div>
        <div class="h-8 w-28 rounded-md bg-slate-200 dark:bg-slate-700"></div>
    </div>
</div>

// frontend/src/components/ads-live/skeleton.tsx
export function Skeleton() {
  return (
    <div className="flex animate-pulse flex-col items-end justify-between gap-4 border-b border-white/10 pb-4 lg:flex-row">
      <div className="flex flex-col gap-2">
        <div className="h-4 w-4 rounded bg-slate-200 dark:bg-slate-700" />
        <div className="h-10 w-72 rounded-lg bg-slate-200 dark:bg-slate-700" />
        <div className="flex gap-2">
          <div className="h-5 w-24 rounded bg-slate-100 dark:bg-slate-800" />
          <div className="h-5 w-16 rounded bg-slate-100 dark:bg-slate-800" />
        </div>
      </div>
      <div className="flex gap-2">
        <div className="h-8 w-20 rounded-md bg-slate-100 dark:bg-slate-800" />
        <div className="h-8 w-28 rounded-md bg-slate-200 dark:bg-slate-700" />
      </div>
    </div>
  )
}
