// frontend-react/src/components/ui/multi-select.tsx
'use client'

import * as React from 'react'
import { Popover as PopoverPrimitive } from '@base-ui/react/popover'

import { cn } from '@/lib/utils'
import { ChevronsUpDown, Check } from 'lucide-react'

export interface MultiSelectOption {
  value: string
  label: string
}

export interface MultiSelectProps {
  options: MultiSelectOption[]
  value: string[]
  onChange: (next: string[]) => void
  placeholder?: string
  searchPlaceholder?: string
  emptyLabel?: string
  className?: string
}

function MultiSelect({
  options,
  value,
  onChange,
  placeholder = 'Select…',
  searchPlaceholder = 'Search…',
  emptyLabel = 'No options',
  className,
}: MultiSelectProps) {
  const [search, setSearch] = React.useState('')

  const filtered = options.filter((o) =>
    o.label.toLowerCase().includes(search.toLowerCase()),
  )

  const selectedLabels = (value ?? []).map(
    (v) => options.find((o) => o.value === v)?.label ?? v,
  )

  function toggle(val: string) {
    const current = value ?? []
    const next = current.includes(val)
      ? current.filter((v) => v !== val)
      : [...current, val]
    onChange(next)
  }

  // Reset search when popover closes
  function handleOpenChange(open: boolean) {
    if (!open) setSearch('')
  }

  const triggerLabel =
    selectedLabels.length > 0 ? selectedLabels.join(', ') : placeholder

  return (
    <PopoverPrimitive.Root onOpenChange={handleOpenChange}>
      <PopoverPrimitive.Trigger
        data-slot="multi-select-trigger"
        aria-label={triggerLabel}
        className={cn(
          'flex min-w-[8rem] items-center justify-between gap-1.5 rounded-lg border border-input bg-transparent px-2.5 py-2 text-sm whitespace-nowrap transition-colors outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-input/30',
          className,
        )}
      >
        {selectedLabels.length === 0 ? (
          <span className="text-muted-foreground">{placeholder}</span>
        ) : (
          <span className="flex flex-wrap gap-1">
            {selectedLabels.map((label) => (
              <span
                key={label}
                className="rounded bg-indigo-50 px-1.5 py-0.5 text-xs font-medium text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300"
              >
                {label}
              </span>
            ))}
          </span>
        )}
        <ChevronsUpDown className="h-4 w-4 shrink-0 text-slate-400" />
      </PopoverPrimitive.Trigger>

      <PopoverPrimitive.Portal>
        <PopoverPrimitive.Positioner sideOffset={4} className="isolate z-50">
          <PopoverPrimitive.Popup
            data-slot="multi-select-content"
            className="w-(--anchor-width) min-w-[10rem] rounded-lg bg-popover text-popover-foreground shadow-md ring-1 ring-foreground/10 duration-100 data-open:animate-in data-open:fade-in-0 data-open:zoom-in-95 data-closed:animate-out data-closed:fade-out-0 data-closed:zoom-out-95"
          >
            {/* Search input */}
            <div className="border-b p-2">
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder={searchPlaceholder}
                className="w-full rounded-md bg-transparent px-1.5 py-1 text-sm outline-none placeholder:text-muted-foreground"
              />
            </div>

            {/* Option list */}
            <div className="max-h-48 overflow-y-auto p-1">
              {filtered.length === 0 ? (
                <p className="py-3 text-center text-xs text-slate-400">
                  {emptyLabel}
                </p>
              ) : (
                filtered.map((option) => {
                  const isSelected = (value ?? []).includes(option.value)
                  return (
                    <button
                      key={option.value}
                      type="button"
                      aria-label={option.label}
                      onClick={() => toggle(option.value)}
                      className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground focus-visible:bg-accent focus-visible:text-accent-foreground focus-visible:outline-none"
                    >
                      {/* Inline check box indicator */}
                      <span
                        className={cn(
                          'flex h-4 w-4 shrink-0 items-center justify-center rounded-[4px] border',
                          isSelected
                            ? 'border-indigo-600 bg-indigo-600 text-white'
                            : 'border-slate-300',
                        )}
                      >
                        {isSelected && <Check className="h-3 w-3" />}
                      </span>
                      {option.label}
                    </button>
                  )
                })
              )}
            </div>
          </PopoverPrimitive.Popup>
        </PopoverPrimitive.Positioner>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  )
}

export { MultiSelect }

// frontend/src/lib/components/ui/multiselect/multi-select.svelte
<script lang="ts">
	import { Popover } from 'bits-ui'
	import { Check, ChevronsUpDown } from 'lucide-svelte'

	let {
		value = $bindable<string[]>([]),
		options,
		placeholder = 'Select…',
		onchange
	}: {
		value?: string[]
		options: { value: string; label: string }[]
		placeholder?: string
		onchange?: (v: string[]) => void
	} = $props()

	let open = $state(false)
	let search = $state('')

	const filtered = $derived(
		options.filter((o) => o.label.toLowerCase().includes(search.toLowerCase()))
	)

	const selectedLabels = $derived(
		(value ?? []).map((v) => options.find((o) => o.value === v)?.label ?? v)
	)

	function toggle(val: string) {
		const next = (value ?? []).includes(val)
			? (value ?? []).filter((v) => v !== val)
			: [...(value ?? []), val]
		value = next
		onchange?.(next)
	}
</script>

<Popover.Root bind:open>
	<Popover.Trigger
		class="flex w-full cursor-pointer items-center justify-between gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-left text-sm focus:ring-2 focus:ring-indigo-500 focus:outline-none dark:border-slate-700 dark:bg-slate-800"
	>
		<div class="flex min-w-0 flex-1 flex-wrap gap-1">
			{#if (value ?? []).length === 0}
				<span class="text-slate-400">{placeholder}</span>
			{:else}
				{#each selectedLabels as label (label)}
					<span
						class="rounded bg-indigo-50 px-1.5 py-0.5 text-xs font-medium text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300"
					>
						{label}
					</span>
				{/each}
			{/if}
		</div>
		<ChevronsUpDown class="h-4 w-4 shrink-0 text-slate-400" />
	</Popover.Trigger>

	<Popover.Content
		class="z-50 mt-1 w-(--bits-popover-anchor-width) min-w-48 rounded-lg border border-slate-200 bg-white p-1 shadow-lg dark:border-slate-700 dark:bg-slate-800"
		align="start"
		sideOffset={4}
	>
		<div class="border-b border-slate-100 px-2 py-1.5 dark:border-slate-700">
			<input
				type="text"
				bind:value={search}
				placeholder="Search…"
				class="w-full bg-transparent text-sm text-slate-900 placeholder-slate-400 focus:outline-none dark:text-white"
			/>
		</div>
		<div class="mt-1 max-h-48 overflow-y-auto">
			{#each filtered as option (option.value)}
				<button
					type="button"
					onclick={() => toggle(option.value)}
					class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm text-slate-700 transition-colors hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700"
				>
					<div
						class="flex h-4 w-4 shrink-0 items-center justify-center rounded border {(
							value ?? []
						).includes(option.value)
							? 'border-indigo-600 bg-indigo-600'
							: 'border-slate-300 dark:border-slate-600'}"
					>
						{#if (value ?? []).includes(option.value)}
							<Check class="h-3 w-3 text-white" />
						{/if}
					</div>
					{option.label}
				</button>
			{/each}
			{#if filtered.length === 0}
				<p class="py-3 text-center text-xs text-slate-400">No options found</p>
			{/if}
		</div>
	</Popover.Content>
</Popover.Root>
