// frontend/src/components/ui/number-field.tsx
import { cn } from '@/lib/utils'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface NumberFieldProps {
  id: string
  label: string
  suffix: string
  value: number
  onValueChange: (n: number) => void
  min?: number
  max?: number
  step?: number
  className?: string
}

function NumberField({
  id,
  label,
  suffix,
  value,
  onValueChange,
  min = 0,
  max,
  step = 1,
  className,
}: NumberFieldProps) {
  return (
    <div className={cn(className)}>
      <Label htmlFor={id} className='mb-1 block text-xs font-medium text-slate-500'>
        {label}
      </Label>
      <div className='relative'>
        <Input
          id={id}
          type='number'
          min={min}
          max={max}
          step={step}
          value={value}
          onChange={(e) => onValueChange(Number(e.target.value))}
          className='pr-8'
        />
        <span className='pointer-events-none absolute top-1/2 right-3 -translate-y-1/2 text-xs text-slate-400'>
          {suffix}
        </span>
      </div>
    </div>
  )
}

export { NumberField }
export type { NumberFieldProps }

// frontend/src/lib/components/ui/input/number-field.svelte
<script lang="ts">
	import Input from './input.svelte'
	import Label from '../label/label.svelte'

	let {
		id,
		label,
		suffix,
		value = $bindable(),
		min = 0,
		max,
		step = 1,
		class: className = ''
	}: {
		id: string
		label: string
		suffix: string
		value: number
		min?: number
		max?: number
		step?: number
		class?: string
	} = $props()
</script>

<div class={className}>
	<Label for={id} class="mb-1 block text-xs font-medium text-slate-500">{label}</Label>
	<div class="relative">
		<Input {id} type="number" {min} {max} {step} bind:value class="pr-8" />
		<span class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs text-slate-400">{suffix}</span>
	</div>
</div>
