// frontend/src/lib/components/ui/dialog/confirm-dialog.svelte
<script lang="ts">
	import { TriangleAlert } from 'lucide-svelte'
	import * as Dialog from './index'

	let {
		open = $bindable(false),
		title = 'Are you sure?',
		description = 'This action cannot be undone.',
		confirmLabel = 'Delete',
		cancelLabel = 'Cancel',
		isLoading = false,
		onconfirm
	}: {
		open: boolean
		title?: string
		description?: string
		confirmLabel?: string
		cancelLabel?: string
		isLoading?: boolean
		onconfirm: () => void
	} = $props()
</script>

<Dialog.Root bind:open>
	<Dialog.Content class="max-w-sm p-0">
		<Dialog.Header>
			<div class="flex items-start gap-3">
				<div
					class="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-red-100 dark:bg-red-900/30"
				>
					<TriangleAlert class="h-5 w-5 text-red-600 dark:text-red-400" />
				</div>
				<div>
					<Dialog.Title>{title}</Dialog.Title>
					<Dialog.Description class="mt-1">{description}</Dialog.Description>
				</div>
			</div>
		</Dialog.Header>
		<Dialog.Footer>
			<Dialog.Close
				class="rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"
			>
				{cancelLabel}
			</Dialog.Close>
			<button
				onclick={onconfirm}
				disabled={isLoading}
				class="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-red-700 disabled:opacity-50"
			>
				{isLoading ? 'Deleting…' : confirmLabel}
			</button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>

// frontend-react/src/components/ui/confirm-dialog.tsx
import { TriangleAlert } from 'lucide-react'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

interface ConfirmDialogProps {
  open: boolean
  onOpenChange?: (open: boolean) => void
  title?: string
  description?: string
  confirmLabel?: string
  cancelLabel?: string
  isLoading?: boolean
  onConfirm: () => void
}

function ConfirmDialog({
  open,
  onOpenChange,
  title = 'Are you sure?',
  description = 'This action cannot be undone.',
  confirmLabel = 'Delete',
  cancelLabel = 'Cancel',
  isLoading = false,
  onConfirm,
}: ConfirmDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-sm p-0" showCloseButton={false}>
        <DialogHeader className="p-4 pb-0">
          <div className="flex items-start gap-3">
            <div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-red-100 dark:bg-red-900/30">
              <TriangleAlert className="h-5 w-5 text-red-600 dark:text-red-400" />
            </div>
            <div>
              <DialogTitle>{title}</DialogTitle>
              <DialogDescription className="mt-1">
                {description}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>
        <DialogFooter>
          <DialogClose render={<Button variant="outline" />}>
            {cancelLabel}
          </DialogClose>
          <Button
            className={cn(
              'bg-red-600 text-white hover:bg-red-700',
              'focus-visible:ring-red-500/50',
            )}
            disabled={isLoading}
            onClick={onConfirm}
          >
            {isLoading ? 'Deleting…' : confirmLabel}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export { ConfirmDialog }
