// frontend/src/lib/components/ui/data-table/data-table.svelte
<script lang="ts" generics="TData, TValue">
	import {
		getCoreRowModel,
		getPaginationRowModel,
		getSortedRowModel,
		getFilteredRowModel,
		type ColumnDef,
		type PaginationState,
		type SortingState,
		type ColumnFiltersState
	} from '@tanstack/table-core'
	import { createSvelteTable, FlexRender } from './index.js'
	import * as Table from '$lib/components/ui/table/index.js'
	import { Search } from 'lucide-svelte'
	import { type Snippet, untrack } from 'svelte'
	import * as m from '$lib/paraglide/messages.js'

	let {
		data,
		columns,
		pageSize = 50,
		searchPlaceholder = 'Search...',
		searchColumn,
		toolbar,
		isLoading = false,
		meta
	} = $props<{
		data: TData[]
		columns: ColumnDef<TData, TValue>[]
		pageSize?: number
		searchPlaceholder?: string
		searchColumn?: string
		toolbar?: Snippet<[table: any]>
		isLoading?: boolean
		meta?: any
	}>()

	let pagination = $state<PaginationState>({ pageIndex: 0, pageSize: untrack(() => pageSize) })
	let sorting = $state<SortingState>([])
	let columnFilters = $state<ColumnFiltersState>([])

	const table = createSvelteTable({
		get data() {
			return data
		},
		get columns() {
			return columns
		},
		state: {
			get pagination() {
				return pagination
			},
			get sorting() {
				return sorting
			},
			get columnFilters() {
				return columnFilters
			}
		},
		get meta() {
			return meta
		},
		onPaginationChange: (updater) => {
			if (typeof updater === 'function') {
				pagination = updater(pagination)
			} else {
				pagination = updater
			}
		},
		onSortingChange: (updater) => {
			if (typeof updater === 'function') {
				sorting = updater(sorting)
			} else {
				sorting = updater
			}
		},
		onColumnFiltersChange: (updater) => {
			if (typeof updater === 'function') {
				columnFilters = updater(columnFilters)
			} else {
				columnFilters = updater
			}
		},
		getCoreRowModel: getCoreRowModel(),
		getPaginationRowModel: getPaginationRowModel(),
		getSortedRowModel: getSortedRowModel(),
		getFilteredRowModel: getFilteredRowModel()
	})

	// Local search value for better reactivity in the input field
	let searchValue = $state('')
	$effect(() => {
		const value = searchValue
		untrack(() => {
			if (searchColumn) {
				table.getColumn(searchColumn)?.setFilterValue(value)
			}
		})
	})

	// Derived rows to ensure Svelte 5 tracks table updates
	const rows = $derived(table.getRowModel().rows)
</script>

<div class="space-y-4">
	<div class="flex items-center justify-between gap-2">
		<div class="flex items-center gap-2">
			{#if searchColumn}
				<div class="relative">
					<Search class="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-slate-400" />
					<input
						type="text"
						placeholder={searchPlaceholder}
						bind:value={searchValue}
						class="w-64 rounded-md border border-slate-300 bg-white py-1.5 pr-4 pl-9 text-sm focus:ring-2 focus:ring-indigo-500 focus:outline-none dark:border-slate-700 dark:bg-slate-900"
					/>
				</div>
			{/if}
			{@render toolbar?.(table)}
		</div>
	</div>

	<div
		class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"
	>
		<div class="overflow-x-auto">
			<Table.Root class="w-full text-left text-sm">
				<Table.Header
					class="border-b border-slate-200 bg-slate-50 text-slate-500 dark:border-slate-800 dark:bg-slate-800/50 dark:text-slate-400"
				>
					{#each table.getHeaderGroups() as headerGroup (headerGroup.id)}
						<Table.Row>
							{#each headerGroup.headers as header (header.id)}
								<Table.Head class="px-6 py-3 font-semibold">
									{#if !header.isPlaceholder}
										<button
											type="button"
											class="flex items-center gap-2 {header.column.getCanSort()
												? 'cursor-pointer select-none hover:text-slate-900 dark:hover:text-white'
												: ''}"
											onclick={header.column.getToggleSortingHandler()}
										>
											<FlexRender
												content={header.column.columnDef.header}
												context={header.getContext()}
											/>
											{#if header.column.getIsSorted()}
												<span class="text-indigo-500">
													{header.column.getIsSorted() === 'asc' ? '↑' : '↓'}
												</span>
											{/if}
										</button>
									{/if}
								</Table.Head>
							{/each}
						</Table.Row>
					{/each}
				</Table.Header>
				<Table.Body class="divide-y divide-slate-200 dark:divide-slate-800">
					{#if isLoading}
						{#each Array(5) as _}
							<Table.Row class="animate-pulse">
								{#each columns as _}
									<Table.Cell class="px-6 py-4">
										<div class="h-4 w-full rounded bg-slate-100 dark:bg-slate-800"></div>
									</Table.Cell>
								{/each}
							</Table.Row>
						{/each}
					{:else}
						{#each rows as row (row.id)}
							<Table.Row
								class="group transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/50"
								data-state={row.getIsSelected() && 'selected'}
							>
								{#each row.getVisibleCells() as cell (cell.id)}
									<Table.Cell class="px-6 py-4">
										<FlexRender
											content={cell.column.columnDef.cell}
											context={cell.getContext()}
										/>
									</Table.Cell>
								{/each}
							</Table.Row>
						{:else}
							<Table.Row>
								<Table.Cell colspan={columns.length} class="px-6 py-8 text-center text-slate-500">
									{m['globals:no_options']()}
								</Table.Cell>
							</Table.Row>
						{/each}
					{/if}
				</Table.Body>
			</Table.Root>
		</div>
	</div>

	{#if table.getPageCount() > 1}
		<div class="flex items-center justify-between px-2 py-4">
			<div class="text-sm text-slate-500 dark:text-slate-400">
				Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount()}
			</div>
			<div class="flex items-center gap-2">
				<button
					class="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium transition-colors hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:hover:bg-slate-800"
					onclick={() => table.previousPage()}
					disabled={!table.getCanPreviousPage()}
				>
					{m['globals:previous']()}
				</button>
				<button
					class="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium transition-colors hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:hover:bg-slate-800"
					onclick={() => table.nextPage()}
					disabled={!table.getCanNextPage()}
				>
					{m['globals:next']()}
				</button>
			</div>
		</div>
	{/if}
</div>

// frontend-react/src/components/ui/data-table.tsx
import { useState, type ReactNode } from 'react'
import {
  useReactTable,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  flexRender,
  type ColumnDef,
  type ColumnFiltersState,
} from '@tanstack/react-table'
import { Search } from 'lucide-react'

import { cn } from '@/lib/utils'

interface DataTableProps<TData, TValue> {
  columns: ColumnDef<TData, TValue>[]
  data: TData[]
  className?: string
  // Optional features — all off unless the relevant prop is passed, so the
  // bare `data + columns` usages (audit, users) keep their exact behaviour.
  // i18n-decoupled: pagination labels come in as strings (like multi-select).
  isLoading?: boolean
  searchColumn?: string
  searchPlaceholder?: string
  pageSize?: number
  toolbar?: ReactNode
  previousLabel?: string
  nextLabel?: string
}

function DataTable<TData, TValue>({
  columns,
  data,
  className,
  isLoading = false,
  searchColumn,
  searchPlaceholder = 'Search...',
  pageSize,
  toolbar,
  previousLabel = 'Previous',
  nextLabel = 'Next',
}: DataTableProps<TData, TValue>) {
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([])

  const paginated = pageSize !== undefined
  const table = useReactTable({
    data,
    columns,
    state: { columnFilters },
    onColumnFiltersChange: setColumnFilters,
    getCoreRowModel: getCoreRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    ...(paginated ? { getPaginationRowModel: getPaginationRowModel() } : {}),
    ...(paginated ? { initialState: { pagination: { pageSize } } } : {}),
  })

  const searchValue = searchColumn
    ? ((table.getColumn(searchColumn)?.getFilterValue() as string) ?? '')
    : ''

  const showHeader = Boolean(searchColumn) || Boolean(toolbar)

  const table_ = (
    <div
      data-slot="data-table"
      className={cn(
        'overflow-hidden rounded-xl border bg-card ring-1 ring-foreground/10 shadow-sm',
        className,
      )}
    >
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead>
            {table.getHeaderGroups().map((headerGroup) => (
              <tr
                key={headerGroup.id}
                className="border-b bg-slate-50 dark:bg-slate-800/50 text-slate-500 dark:text-slate-400"
              >
                {headerGroup.headers.map((header) => (
                  <th key={header.id} className="px-6 py-3 font-semibold">
                    {header.isPlaceholder
                      ? null
                      : flexRender(
                          header.column.columnDef.header,
                          header.getContext(),
                        )}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody className="divide-y">
            {isLoading ? (
              Array.from({ length: 5 }).map((_, i) => (
                <tr key={i} className="animate-pulse">
                  {columns.map((_, j) => (
                    <td key={j} className="px-6 py-4">
                      <div className="h-4 w-full rounded bg-slate-100 dark:bg-slate-800" />
                    </td>
                  ))}
                </tr>
              ))
            ) : table.getRowModel().rows.length > 0 ? (
              table.getRowModel().rows.map((row) => (
                <tr
                  key={row.id}
                  className="group transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/50"
                >
                  {row.getVisibleCells().map((cell) => (
                    <td key={cell.id} className="px-6 py-4">
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </td>
                  ))}
                </tr>
              ))
            ) : (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-6 py-8 text-center text-slate-500 dark:text-slate-400"
                >
                  No results
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )

  // No optional features → preserve the original single-element output exactly.
  if (!showHeader && !paginated) return table_

  return (
    <div className="space-y-4">
      {showHeader && (
        <div className="flex items-center gap-2">
          {searchColumn && (
            <div className="relative">
              <Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder={searchPlaceholder}
                value={searchValue}
                onChange={(e) =>
                  table.getColumn(searchColumn)?.setFilterValue(e.target.value)
                }
                className="w-64 rounded-md border border-slate-300 bg-white py-1.5 pr-4 pl-9 text-sm focus:ring-2 focus:ring-indigo-500 focus:outline-none dark:border-slate-700 dark:bg-slate-900"
              />
            </div>
          )}
          {toolbar}
        </div>
      )}

      {table_}

      {paginated && table.getPageCount() > 1 && (
        <div className="flex items-center justify-between px-2 py-4">
          <div className="text-sm text-slate-500 dark:text-slate-400">
            Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount()}
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              className="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium transition-colors hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:hover:bg-slate-800"
              onClick={() => table.previousPage()}
              disabled={!table.getCanPreviousPage()}
            >
              {previousLabel}
            </button>
            <button
              type="button"
              className="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium transition-colors hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:hover:bg-slate-800"
              onClick={() => table.nextPage()}
              disabled={!table.getCanNextPage()}
            >
              {nextLabel}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

export { DataTable }
